[package]
name = "valora"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]

[dependencies]
glium = "0.19"
lyon = "0.8"
error-chain = "0.11"
palette = "0.2"
rand = "0.3"
image = "0.18"
petgraph = "0.4.10"
itertools = "0.7.4"
maplit = "1"
lazy_static = "1"